name: Unit tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          check-latest: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Test Core package
        shell: bash
        run: |
          python -m pip install -e packages/pycommander-core
          cd packages/pycommander-core
          python -m unittest discover -s tests -p "test_*.py" -v

      - name: Test CLI package
        shell: bash
        run: |
          python -m pip uninstall -y silabs-pycommander-cli silabs-pycommander-gui
          python -m pip install -e packages/pycommander-cli
          cd packages/pycommander-cli
          python -m unittest discover -s tests -p "test_*.py" -v

      - name: Test GUI package
        shell: bash
        run: |
          python -m pip uninstall -y silabs-pycommander-cli silabs-pycommander-gui
          python -m pip install -e packages/pycommander-gui
          cd packages/pycommander-gui
          python -m unittest discover -s tests -p "test_*.py" -v
